### ISSUE TITLE
Do new parameters need to be saved separately?

### ISSUE THREAD

**Issue by 1050705324** [MaxZanella/CLIP-LoRA#2]
Thanks for your code ！！！
I have problem with new lora parameter save path, is it be saved in the ViT-L-14-336px.pt.

**Comment by MaxZanella** [comment]
Hello,

I completely agree that being able to save and reload the LoRA modules easily would be super helpful. I'll add this functionality to the code and update the readme to include instructions. I'll let you know as soon as it's done, which should be in 1-2 days.

**Comment by rkj12345** [comment]
> Hello,
> 
> I completely agree that being able to save and reload the LoRA modules easily would be super helpful. I'll add this functionality to the code and update the readme to include instructions. I'll let you know as soon as it's done, which should be in 1-2 days.

Thank you for your work. I look forward to your future updates.

**Comment by MaxZanella** [comment]
I have updated the code and the README accordingly. To answer the original question, you will now be able to save the LoRA modules separately (if save_path is provided), which is much more efficient than saving the weights of the whole model. Additionally, you can easily load your LoRA for inference using the --eval_only argument and the corresponding save_path. 
I am closing the issue but feel free to reach out if you have any more questions or need further assistance!

**Comment by 1050705324** [comment]
Oh，thank you very much ! ! ! Your work has helped me a lot.

**Comment by aditya-pola** [comment]
Hi, what is the way to now store the entire CLIP model instead of a seperate LoRA module?
