### ISSUE TITLE
Solved: RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn

### ISSUE THREAD

**Issue by simon-ging** [MaxZanella/CLIP-LoRA#5]
Dear Authors, thank you for your interesting work and for releasing the code.

We found (and probably solved) an issue where the training would break after doing evaluation, in pytorch lightning:

- Train for some steps
- Evaluate
- Start training the next epoch

Result:

```python
print(loss.requires_grad)  # False, the computational graph is broken
# Error Stack:
return Variable._execution_engine.run_backward(  # Calls into the C++ engine to run the backward pass
RuntimeError: element 0 of tensors does not require grad and does not have a grad_fn
```

It seems setting the model to eval and then train somehow conflicts with your code.

We have not verified it but it could be tested by running your clip example code, set VALIDATION=True and uncomment the validation [here](https://github.com/MaxZanella/CLIP-LoRA/blob/main/lora.py#L136)

Either way the fix we found is to run `mark_only_lora_as_trainable(clip_model)` each time we run `model.train()`

In PyTorch lightning this looks like this:

```python
    def on_train_epoch_start(self) -> None:
        super().on_train_epoch_start()
        if self.use_lora:
            self.model.train()
            mark_only_lora_as_trainable(self.model)
```

Maybe this information can help you or others in using the code.

Best,

Simon

**Comment by MaxZanella** [comment]
Hello Simon,

Thank you for your interest in our project and for proposing a quick fix! 
I tried uncommenting our validation (with VALIDATION=True) as you suggested to reproduce the error, but the code continued to train smoothly without any issues.
I am not very familiar with lightning, and it’s a bit complicated for me to help without more information. However, I am more than happy to assist if you can provide additional details.
