### ISSUE TITLE
merge_BA_with_mask

### ISSUE THREAD

**Issue by StrongerPeople** [MaxZanella/CLIP-LoRA#6]
Thank you for providing the code. However, I have a few confused. Firstly, it appears that the merge_BA_with_mask function may not be functioning as intended. Secondly, I've noticed that the number of q, k, v parameters seems to exceed the count of  q, k, v,o parameters. Could you  how it should be addressed?

**Comment by MaxZanella** [comment]
Hello,
Thank you for pointing that out. The merge_BA_with_mask function is a remnant from previous iterations of the code and is not used anymore. I will remove it.
Could you please provide more details regarding your second concern? For example, the code snippet and command line you are using?

**Comment by StrongerPeople** [comment]
Hi,
Thank you for your reply. The second concern is my problem, I placed the mark_only_lora_as_trainable function call before apply_lora, which might be why requires_grad was not initialized to True.
