### ISSUE TITLE
How I want to use your code to train a CLIP, which files are necessary?

### ISSUE THREAD

**Issue by ranck626** [MaxZanella/CLIP-LoRA#7]
[loralib](https://github.com/MaxZanella/CLIP-LoRA/tree/main/loralib)
[lora.py](https://github.com/MaxZanella/CLIP-LoRA/blob/main/lora.py)
May I ask if these two files are the only ones that are necessary.
Looking forward to your reply.

**Comment by MaxZanella** [comment]
Hello,

If you want to apply LoRA to other models similarly to how it's done in this repository, then I suppose yes. However, you should keep the other folders to create the CLIP model, manage datasets, etc., depending on your specific needs.

If you have more specific questions about the project structure, feel free to ask. It would be easier for me to help.
