### ISSUE TITLE
Hugging Face Model Support and link with LLM.

### ISSUE THREAD

**Issue by xiaokj37** [MaxZanella/CLIP-LoRA#8]
Thank you very much for open-sourcing your work.
I am now implementing the connection between CLIP-LoRa and LLM, but it seems that I need to get hidden_state from ViT, which is not provided in the clip folder.
So I am curious whether this work supports HFmodel(CLIPVisionModel support vision_tower(image_tensor, output_hidden_states=True)), or do you have any good suggestions for connecting to LLM?

**Comment by MaxZanella** [comment]
Hello,

If I understand correctly, you want to get the last hidden state of the vision encoder of CLIP ?
You can look into the class CLIP line 239 of clip.py, which contained the method encode_image (a call to the vision encoder of the clip model).
Be aware though that the vision encoder of CLIP has a linear layer on top that projects the last token.  You can see that in the class VisionTransformer line 202 and the end of the corresponding forward method. ou may want to get more tokens than just the last one, and for that, you might need to modify the end of this forward method.

I hope this helps. It's a bit complicated without more details, so feel free to reach out with more specifics.

**Comment by xiaokj37** [comment]
Thanks for your reply.
