### ISSUE TITLE
CLIP-Lora for Image Text Matching Task

### ISSUE THREAD

**Issue by xiaokj37** [MaxZanella/CLIP-LoRA#9]
Is it possible to use clip-lora to complete the ITM task?
Just like the original training of CLIP.
The datasets you gave seem to be all about image classification.

**Comment by MaxZanella** [comment]
Hello,

You are correct that this repository is primarily designed for classification purposes (but not limited to). You can see this in lines 112-113 of lora.py where we use cross-entropy : 
```
cosine_similarity = logit_scale * image_features @ text_features.t()
loss = F.cross_entropy(cosine_similarity, target)
```

If you're looking to implement Image-Text Matching (ITM), you might want to modify those lines to something similar to the original CLIP approach (I didn't try them though, so take that with care, it may need adaptation):

```
logits_per_image = logit_scale * image_features @ text_features.T
logits_per_text = logit_scale * text_features @ image_features.T

batch_size = image_features.shape[0]
labels = torch.arange(batch_size, device=device).long()
total_loss = (
    F.cross_entropy(logits_per_image, labels) +
    F.cross_entropy(logits_per_text, labels)
) / 2
```

I hope this helps!

**Comment by yayunlei** [comment]
> Is it possible to use clip-lora to complete the ITM task? Just like the original training of CLIP. The datasets you gave seem to be all about image classification.

hello~ I have the same purpose. Did you find a good way to continuous training of clip in a small dataset for ITM task?
